Add FAQ section
ubclaunchpad/ubclaunchpad.github.io-old pull request #49
Opened 2018-04-21 19:49 UTC by bfbachmann

## Changes
* Add FAQ section. It looks like the Team section (with the accordions that you can drop down).
* Refactor some code in team.js to only operate on DOM elements we created from the result of our `fetch` instead of getting _all_ elements of class `accordion` and `panel`.

2018-04-22 00:20 UTC, bobheadxi reviewed
I think "Why should I apply?" might be a good FAQ question as well - talk about what Launch Pad has to offer in more detail

2018-04-22 00:20 UTC, bobheadxi commented on index.html
> +          As a Launch Pad member you will be expected to attend meetings every Saturday from 11am-3pm, complete the ticket assigned
This works but might come across as a little dry (tech leads boss everyone around). Maybe something like this? A bit more emphasis on the "team" part and play up the role of team members:

> Launch Pad projects are all team projects, and as a part of a team, you will need to contribute in order to advance both your team's project, and your own l33t hacker skills. Thus, you will be expected to attend meetings every Saturday from 11am to 3pm, where you will discuss the week's goals with your team and decide on what tasks need to be done. You will also be expected to complete or make progress on whatever task is assigned to you that week (or let your team lead know a week in advance if you have to miss a meeting or are too busy to complete a ticket), and to be available on Slack throughout the week.

2018-04-22 00:32 UTC, bobheadxi commented
Also this might be too much, but there are some really kind comments in the Tech Leads Survey - might be fun to have some of those on the site too lol, a "victims' testimony" of sorts, add it to FAQ for "Why should I apply?" 😅

2018-04-23 05:10 UTC, bfbachmann commented on index.html
> +          As a Launch Pad member you will be expected to attend meetings every Saturday from 11am-3pm, complete the ticket assigned
That's a good point! I'll update it. I also think your suggestion about adding a "Why should I apply?" section is good.

2018-04-23 06:12 UTC, bobheadxi commented
Unfortunately looks a bit too skinny on mobile 😢 not sure if there's much that can be done though

![img_bad83fbba45a-1](https://user-images.githubusercontent.com/23356519/39109632-8c1d8032-4682-11e8-9354-76f80f1da0f2.jpeg)

2018-04-23 06:12 UTC, bobheadxi approved these changes

2018-04-23 06:13 UTC, bfbachmann commented
Damn. Excellent catch!

2018-04-28 18:56 UTC, bfbachmann commented
@bobheadxi The styles should be fixed now!

2018-04-28 19:02 UTC, frostyshadows requested changes
looks good, two minor things

2018-04-28 19:02 UTC, frostyshadows commented on index.html
> +          with valueable resources like cloud services, and we ensure that each team has a great technical lead who will
should be valuable

2018-04-28 19:02 UTC, frostyshadows commented on index.html
> +          more members while still maintaining a good experience for everyone in the club.
we can also mention that it can benefit the applicant as well unless you think the section will be too long. For many applicants, it's their first technical interview, and it helps them learn what to expect from a co-op interview in a welcoming environment.

2018-04-28 19:04 UTC, bfbachmann commented on index.html
> +          with valueable resources like cloud services, and we ensure that each team has a great technical lead who will
Thanks!

2018-04-28 20:25 UTC, frostyshadows approved these changes

2018-05-01 04:28 UTC, merged