Recruitment page remodelled
ubclaunchpad/ubclaunchpad.github.io-old pull request #74
Opened 2019-09-01 03:01 UTC by Annnnnieee

added jenny's recruitment page to the join us section.

2019-09-01 04:32 UTC, Schemetrical approved these changes
Looks good, just a small nit. Also, the video is broken on my local but I assume it's working (might be an issue if you find it broken too). Otherwise lgtm

2019-09-01 04:32 UTC, Schemetrical commented on index.html
> +        <p>Are you a programmer, designer, or business student looking for an opportunity to work on interesting
Can we add some spacing (possibly 8px or something) above this? Just looks a bit close right now

2019-09-01 04:33 UTC, Schemetrical requested changes
oops forgot about this. Just a mistype probably, easy fix

2019-09-01 04:33 UTC, Schemetrical commented on index.html
> +          <a id="nav-projects" href="#projects">PROJ  ECTS</a>
This might need to be undone

2019-09-01 04:48 UTC, Annnnnieee commented on index.html
> +          <a id="nav-projects" href="#projects">PROJ  ECTS</a>
oops! ha

2019-09-01 05:48 UTC, Annnnnieee commented
looks like the reason the video wasn't playing was because mp4 isn't supported on a number of browsers. I changed it to webm. still wont work on opera, but no one uses opera

2019-09-01 05:51 UTC, Annnnnieee commented
Also, jenny wanted the join section to stand alone instead of inline with the rest of the page, so I moved it out.

2019-09-01 05:51 UTC, Schemetrical commented
I’ll check tomorrow sometime. This deploy preview thing is nice but I don’t see the video on mobile safari. Bout to take off :)

2019-09-01 05:55 UTC, Annnnnieee commented
ahh.. looks like safari also doesn't support webm.

2019-09-01 05:55 UTC, Annnnnieee commented
bye!

2019-09-03 21:17 UTC, Schemetrical approved these changes

2019-09-04 01:35 UTC, merged